language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - git clone --branch master --depth 1 https://github.com/libuv/libuv
    - cd libuv && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install

before_script:
    - ./autogen.sh

